name: Deploy to EC2

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t "${{ secrets.HUBACC }}"/calculatorapp:latest .
      
      - name: Docker Login
        run: echo "${{ secrets.HUBPW }}" | docker login -u "${{ secrets.HUBACC }}" --password-stdin

      - name: Docker push
        run: |
          docker push "${{ secrets.HUBACC }}"/calculatorapp:latest

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSHKEY}}" > ~/.ssh/meinPrivateKey
          chmod 600 ~/.ssh/meinPrivateKey
          ssh-keyscan -H ${{secrets.EC2IP}} >> ~/.ssh/known_hosts

      - name: SSH Connection to EC2
        run: |
          ssh -i ~/.ssh/meinPrivateKey ec2-user@${{ secrets.EC2IP }} << 'ENDSSH'    
              sudo yum update -y
              sudo yum upgrade -y
              sudo yum install docker -y
              sudo systemctl enable docker.service
              sudo systemctl start docker
              sudo usermod -aG docker ec2-user
              sudo docker pull "${{ secrets.HUBACC }}"/calculatorapp:latest
          ENDSSH

      - name: Start Docker Container on EC2 instance
        run: |
            ssh -i ~/.ssh/meinPrivateKey ec2-user@${{ secrets.EC2IP }} << 'ENDSSH'
                docker run -d -p 80:3000 --name calculatorapp "${{ secrets.HUBACC }}"/calculatorapp:latest
            ENDSSH

      - name: Clean Up SSH Key File (optional)
        run: |
          if [ -f ~/.ssh/meinPrivateKey ]; then rm ~/.ssh/meinPrivateKey; fi
